### ISSUE TITLE
Placement of editor div

### ISSUE THREAD

**Issue by j-frost** [navisayslisten/AceEditorVTT#3] opened 2020-12-05 16:49 UTC
When editing a macro in the default macro popup box size, the footer seems to block out a part of the editor. For my setup that meant it only showed the first six lines. 

When I resized the window, it became apparent that something was wrong. Also see screenshots

before resize

![image](https://user-images.githubusercontent.com/6002677/101258313-fe032700-3721-11eb-9164-ffac8ac368b1.png)

after resize

![image](https://user-images.githubusercontent.com/6002677/101258330-183d0500-3722-11eb-912b-dc75a0661ee9.png)

I'm using FoundryVTT 0.7.8

**Comment by j-frost** [comment] 2020-12-05 16:51
Quickfix/Workaround: 
```css
element.style {
  height: 100% !important;
  margin: 0;
}
```

**Comment by navisayslisten** [comment] 2020-12-06 23:09
Hey @j-frost . Thanks for the post. Would you mind giving some more details? I need browser version, operating system, etc.
Oh also, what other modules do you have installed?

When I try to reproduce this issue I am unable to see the same bug. Also updated to 0.7.8 and tested on the Foundry app for Windows, Firefox (83) and Chrome (87).
![image](https://user-images.githubusercontent.com/27226232/101295862-59deb600-37dd-11eb-96e5-42bc14d54065.png)

**Comment by navisayslisten** [comment] 2020-12-06 23:14
Oh, I actually see what you might think the issue is. The line numbers on the left will not continue if you don't type more lines.
![image](https://user-images.githubusercontent.com/27226232/101295976-0882f680-37de-11eb-896b-23b8febd48b1.png)

This is working as intended. I am closing this issue.

**Comment by navisayslisten** [comment] 2020-12-06 23:15
Hmm it's possible I'm still misunderstanding. Will re-open. Was too hasty.

**Comment by j-frost** [comment] 2020-12-08 10:46
Hey @navisayslisten of course I can. I'm running Foundry self hosted on an Ubuntu 20.10 `Linux foundry-vtt-ubuntu-20-10 5.8.0-1012-gcp #12-Ubuntu SMP Mon Nov 16 13:07:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`. Foundry is version 0.7.8; AceEditorVTT is 0.2.5. 

I initially tried accessing it from a Windows `Version 10.0.19042 Build 19042` PC running Chrome `Version 87.0.4280.88 (Official Build) (64-bit)` and Firefox `83.0 (64-bit)`. I've since also tried on my Chromebook, with Chrome running `Version 88.0.4324.22 (Official Build) beta (64-bit)`. The issue persists across all of those browsers. 

If you need any more information to debug this problem, I'll be happy to help :)

**Comment by j-frost** [comment] 2020-12-08 14:49
Ah also I'm on 1080p resolution on both devices.

**Comment by navisayslisten** [comment] 2020-12-12 05:23
It's starting to look like I will have to create compatibility for Ubuntu UI, as those devices have some pretty drastic display changes compared to Windows. I don't own a Mac to try changes there too, but will have to consider those devices might have some UI differences too. Give me some time to figure out how to conditionally format the window based on device OS.

To clarify, I can only reproduce the issue on Linux. If I make changes, I see similar Windows UI breaks to what you're seeing.

**Comment by navisayslisten** [comment] 2020-12-12 05:46
@j-frost See if the latest package I just pushed helps at all. If not I'll keep this issue up while trying to figure out where the differences are. These changes didn't break any features for me. An annoying new limitation is that with 1080p you're only going to see about 30 lines total, given the largest possible Macro Editor window scale (and a small-ish font size). But better than only 6.

**Comment by RobinKuiper** [comment] 2020-12-12 11:15
I just found out about this module and I love it. But I have the same thing @j-frost has.

https://i.imgur.com/NLfQ0li.png

**Client**
**System:** Windows 10
**Browser:** Chrome Version 86.0.4240.193 (Official Build) (64-bit)

**Hosting Server:** Ubuntu 20.04

The quickfix helps btw.

**Comment by j-frost** [comment] 2020-12-12 13:09
Alright I just updated and now I'm getting this on Windows+Chrome: 

![image](https://user-images.githubusercontent.com/6002677/101984729-98fc8380-3c83-11eb-8503-4ac65ca93eeb.png)

So 13 rows, but the editor `div` element is still somehow misaligned.

**Comment by navisayslisten** [comment] 2020-12-16 20:05
It's really strange. I can't reproduce either of your issues on similar versions. The one difference I can point out is I'm on Chrome 87. Other than that I'm currently streaming programming on v0.2.6 and can't reproduce this. I might need more details to assist both of you.

**Comment by navisayslisten** [comment] 2020-12-16 20:09
If either of you are still tracking this issue, please send me a list of modules you have enabled alongside Ace Editor if any. Otherwise I cannot reproduce or fix the apparently inconsistent bug. https://www.twitch.tv/videos/839691375

**Comment by j-frost** [comment] 2020-12-16 21:16
Good news everyone! I can reproduce it even with no other modules enabled! /s

But seriously, if I can provide any further details, let me know. Alternatively, I'm open to setting up a screen sharing session or similar.

**Closed as completed** 2021-08-28 14:02 UTC
Labels: bug
